### ISSUE TITLE
No data is being downloaded

### ISSUE THREAD

**Issue by Utfard** [asavinov/intelligent-trading-bot#16]
Hello , 
I made a simple config.json from config-sample-v0.2.0.json with Binaance API Key and telegram key, let it ran for a while, no data is being downloaded. 

It starts with : 
Start downloading 'BTCUSDT' ...
File not found. All data will be downloaded and stored in newly created file.
Downloading all available 1m data for BTCUSDT. Be patient..!
..and stays like that forever. 
Maybe some binance endpoint was changed in the meanwhile ?

**Comment by asavinov** [comment]
config-sample-v0.2.0.json is some old release so it is better to try with the latest config-sample-v0.4.0.json

If it prints "Be patient" then this means that the ``python-binance`` library requests the data (so everything is ok). Normally it takes quite some time for the first time. If it really does not end in an hour or so then something is wrong in ``python-binance`` - check that you use the latest version.

**Comment by Utfard** [comment]
Thank you, I sorted it out in the meanwhile - my mistake. Issue can be closed.
Will it run on different pair , EGLDUSDT for example, or it has some hard coded stuff for BTC ?
