### ISSUE TITLE
Sample of config file

### ISSUE THREAD

**Issue by dooke** [asavinov/intelligent-trading-bot#3]
Do you have a sample of your config file ? 
All scripts have "freq" option hard coded ? 

I have an error with "freq": "1h" but no idea oh problem trying to debug df

lightgbm.basic.LightGBMError: Check failed: (num_data) > (0) at /Users/runner/work/1/s/python-package/compile/src/io/dataset.cpp, line 33

Can we have a bit more documentation ?

Thx

**Comment by asavinov** [comment]
_> All scripts have "freq" option hard coded ?_
_> I have an error with "freq": "1h" but no idea oh problem trying to debug df_

Yes, most of the scripts assume 1m frequency. I have never tried other (lower) frequencies (although it might be useful for more general scenarios).

_> Can we have a bit more documentation ?_

Which script or step does not work for you and where it fails? Then I could add more details on the implicit assumptions and usage.

Here is the config.json I am using for all steps (except for trading):
```
{
  "api_key": "my_key",
  "api_secret": "my_secret",

  "telegram_bot_token": "source_id",
  "telegram_chat_id": "destination_id",

  "symbol": "BTCUSDT",
  "base_asset": "BTC",
  "quote_asset": "USDT",

  "data_folder": "C:/DATA2/BITCOIN/GENERATED/BTCUSDT",
  "model_folder": "C:/DATA2/BITCOIN/MODELS/BTCUSDT"
}
```

**Comment by dooke** [comment]
Thank you for this add in documentation and your reply ;)

I used in configuration variable the keys collector.depth.freq for playing with frequency in scripts replacing the line
```python
freq = App.config["collector"]["depth"]["freq"]
```
to
```python
freq = App.config["collector"]["depth"]["freq"]
```

Also added package "tqdm" in requirements.txt - library required in download, merge and depth scripts

For LightGBMError it was my fault i don't installed this package and i have switched between linux & mac.

Try to discover more ;)
Thx
