### ISSUE TITLE
Configs samples

### ISSUE THREAD

**Issue by StateException** [asavinov/intelligent-trading-bot#8]
Hello! Сould you update the sample configs? Because it seems there are not enough parameters for the full functionality of the scripts, for example "time_column" is missing at all, as well as "freq". I tried to start training several times, but the process was interrupted several times due to incorrect training configuration.

Sincerely!

**Comment by StateException** [comment]
If what I'm talking about is "config-sample-v0.3.0.json", it doesn't exactly match what's in "App.py". Therefore, I would be very grateful if you would set such "standard" settings. It is quite possible that other beginners who are not quite versed in python will also need it.

**Comment by asavinov** [comment]
Hi, I am currently doing some refactorings and many configuration parameters change indeed (and not all components are working). As soon as I get a more or less stable (new) version, I will publish a working sample config. Sorry for not having it right now.

**Comment by StateException** [comment]
Np, mate. Thanks for quick answer! Could you tell me if in the releases the archive of version 0.3.0 everything corresponds to "config-sample-v0.3.0.json" there?

**Comment by asavinov** [comment]
Yes, I added config-sample-v0.3.0.json to match version 0.3.0 of code. 
My Python version is 3.8.
